#!/bin/bash
set -e

PROJECT_NAME="$1"
REPO_PATH="$2"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="${ROOT_DIR}/projects/${PROJECT_NAME}"
CONTEXT_FILE="${PROJECT_DIR}/project-context.md"

if [ -z "$PROJECT_NAME" ] || [ -z "$REPO_PATH" ]; then
    echo "Usage: $0 <project-name> <path-to-repo>"
    echo "Example: $0 my-project /home/user/projects/my-project"
    exit 1
fi

if [ ! -d "$PROJECT_DIR" ]; then
    echo "Error: Project '$PROJECT_NAME' not found at $PROJECT_DIR"
    echo "Run 'make new-project name=$PROJECT_NAME' first."
    exit 1
fi

if [ ! -d "$REPO_PATH" ]; then
    echo "Error: Repo not found at $REPO_PATH"
    exit 1
fi

echo "Scanning project repo: $REPO_PATH"
echo "Updating context for: $PROJECT_NAME"
echo ""

# Detect tech stack
TECH_INFO=""
FRAMEWORK=""
LANGUAGE=""
DATABASE=""
BUILD_TOOL=""
TEST_TOOL=""
PACKAGE_MANAGER=""

# PHP/Laravel detection
if [ -f "$REPO_PATH/composer.json" ]; then
    LANGUAGE="PHP"
    PACKAGE_MANAGER="Composer"
    if grep -q "laravel/framework" "$REPO_PATH/composer.json" 2>/dev/null; then
        FRAMEWORK="Laravel"
        LARAVEL_VER=$(grep -o '"laravel/framework": "[^"]*"' "$REPO_PATH/composer.json" | grep -o '[0-9]*\.' | head -1)
        FRAMEWORK="Laravel ${LARAVEL_VER}x"
    fi
    if grep -q "phpunit" "$REPO_PATH/composer.json" 2>/dev/null; then
        TEST_TOOL="PHPUnit"
    fi
    if grep -q "nuwave/lighthouse" "$REPO_PATH/composer.json" 2>/dev/null; then
        TECH_INFO="${TECH_INFO}API: GraphQL (Lighthouse)\n"
    fi
fi

# Node/JS detection
if [ -f "$REPO_PATH/package.json" ]; then
    if [ -z "$LANGUAGE" ]; then
        LANGUAGE="JavaScript/TypeScript"
    fi
    if grep -q "\"vue\"" "$REPO_PATH/package.json" 2>/dev/null; then
        TECH_INFO="${TECH_INFO}Frontend: Vue.js\n"
    fi
    if grep -q "\"react\"" "$REPO_PATH/package.json" 2>/dev/null; then
        TECH_INFO="${TECH_INFO}Frontend: React\n"
    fi
    if grep -q "\"vite\"" "$REPO_PATH/package.json" 2>/dev/null; then
        BUILD_TOOL="Vite"
    elif grep -q "\"webpack\"" "$REPO_PATH/package.json" 2>/dev/null; then
        BUILD_TOOL="Webpack"
    fi
    if grep -q "\"vitest\"" "$REPO_PATH/package.json" 2>/dev/null; then
        TEST_TOOL="${TEST_TOOL:+$TEST_TOOL + }Vitest"
    elif grep -q "\"jest\"" "$REPO_PATH/package.json" 2>/dev/null; then
        TEST_TOOL="${TEST_TOOL:+$TEST_TOOL + }Jest"
    fi
fi

# Docker detection
if [ -f "$REPO_PATH/docker-compose.yml" ] || [ -f "$REPO_PATH/docker/docker-compose.yml" ]; then
    TECH_INFO="${TECH_INFO}Infrastructure: Docker Compose\n"
fi

# Database detection
if [ -f "$REPO_PATH/.env.example" ]; then
    if grep -q "DB_CONNECTION=mysql" "$REPO_PATH/.env.example" 2>/dev/null; then
        DATABASE="MySQL"
    elif grep -q "DB_CONNECTION=pgsql" "$REPO_PATH/.env.example" 2>/dev/null; then
        DATABASE="PostgreSQL"
    elif grep -q "DB_CONNECTION=sqlite" "$REPO_PATH/.env.example" 2>/dev/null; then
        DATABASE="SQLite"
    fi
fi
if [ -f "$REPO_PATH/src/.env.example" ]; then
    if grep -q "DB_CONNECTION=mysql" "$REPO_PATH/src/.env.example" 2>/dev/null; then
        DATABASE="MySQL"
    elif grep -q "DB_CONNECTION=pgsql" "$REPO_PATH/src/.env.example" 2>/dev/null; then
        DATABASE="PostgreSQL"
    fi
fi

# Makefile detection
MAKEFILE_TARGETS=""
if [ -f "$REPO_PATH/Makefile" ]; then
    MAKEFILE_TARGETS=$(grep -E "^[a-zA-Z_-]+:.*##" "$REPO_PATH/Makefile" | head -10 | awk -F':.*##' '{printf "| `make %s` | %s |\n", $1, $2}')
fi

# Existing .kiro detection
HAS_KIRO="No"
if [ -d "$REPO_PATH/.kiro/steering" ]; then
    HAS_KIRO="Yes ($(ls "$REPO_PATH/.kiro/steering/"*.md 2>/dev/null | wc -l) steering files)"
fi

# Generate summary
echo "=== Detected ==="
echo "Language: ${LANGUAGE:-Unknown}"
echo "Framework: ${FRAMEWORK:-Unknown}"
echo "Database: ${DATABASE:-Unknown}"
echo "Build: ${BUILD_TOOL:-Unknown}"
echo "Testing: ${TEST_TOOL:-Unknown}"
echo "Existing .kiro/: $HAS_KIRO"
echo -e "$TECH_INFO"
echo ""

# Write discovered info to a detection file (AI can use this to fill context)
DETECTION_FILE="${PROJECT_DIR}/.detected-stack.md"
cat > "$DETECTION_FILE" << EOF
# Auto-Detected Project Stack

> Generated by \`make link-project\`. Use this to fill in \`project-context.md\` and steering templates.
> Delete this file after project-context.md is filled.

## Detected Info

| Component | Detected Value |
|---|---|
| Language | ${LANGUAGE:-Unknown} |
| Framework | ${FRAMEWORK:-Unknown} |
| Database | ${DATABASE:-Unknown} |
| Build Tool | ${BUILD_TOOL:-Unknown} |
| Testing | ${TEST_TOOL:-Unknown} |
| Package Manager | ${PACKAGE_MANAGER:-Unknown} |
| Existing .kiro/ | ${HAS_KIRO} |

## Additional
$(echo -e "$TECH_INFO" | sed 's/^/- /')

## Repo Path

\`$REPO_PATH\`

## Key Files Found

$([ -f "$REPO_PATH/composer.json" ] && echo "- composer.json ✅")
$([ -f "$REPO_PATH/package.json" ] && echo "- package.json ✅")
$([ -f "$REPO_PATH/Makefile" ] && echo "- Makefile ✅")
$([ -f "$REPO_PATH/docker-compose.yml" ] && echo "- docker-compose.yml ✅")
$([ -d "$REPO_PATH/docker" ] && echo "- docker/ ✅")
$([ -f "$REPO_PATH/.env.example" ] && echo "- .env.example ✅")
$([ -f "$REPO_PATH/src/.env.example" ] && echo "- src/.env.example ✅")
$([ -d "$REPO_PATH/.kiro" ] && echo "- .kiro/ ✅")
$([ -f "$REPO_PATH/README.md" ] && echo "- README.md ✅")

## Makefile Targets (if found)

| Command | Description |
|---|---|
${MAKEFILE_TARGETS:-| — | No Makefile targets detected |}

## Next Steps

1. Open \`project-context.md\` and fill in project details using detected info above
2. In a Kiro session, say: "Read \`projects/${PROJECT_NAME}/.detected-stack.md\` and help me fill in \`project-context.md\`"
3. Delete this file once project-context.md is complete
EOF

echo "✅ Detection complete. Written to: $DETECTION_FILE"
echo ""
echo "Next: Open a Kiro session and say:"
echo "  Read projects/${PROJECT_NAME}/.detected-stack.md and help me fill in project-context.md"
